### ISSUE TITLE
please create tags for releases

### ISSUE THREAD

**Issue by pravi** [regexhq/path-root-regex#2]
we take github tarballs to create debian packages. Another option would be to include tests in dist tarballs so we can run tests during build.

**Comment by tunnckoCore** [comment]
https://github.com/regexhq/path-root-regex/commit/89452d93fab36c9927d24c2779fedfe81f23279c

@jonschlinkert should just publish :)

**Comment by ObserverHerb** [comment]
Would like this as well for packaging for Gentoo.

**Comment by tunnckoCore** [comment]
Is just the latest release enough?

I just created a release/tag for the `0.1.2`
